import Head from 'next/head';
import Image from 'next/image';
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <div
      className="text-center bg-dark d-flex justify-content-center align-items-center"
      style={{ height: '100vh' }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="text-white">
          Welcome to <a href="https://nextjs.org">Next.js!</a> +{' '}
          <a href="https://react-bootstrap.github.io/">Bootstrap</a>
        </h1>

        <p className="text-white mt-4">
          Get started by editing{' '}
          <code className="bg-white p-2">pages/index.js</code>
        </p>
        <a href="https://ineuron.ai">
          <Image
            src="/logo-light.png"
            alt="ineuron-logo"
            height={70}
            width={140}
          />
        </a>
      </main>
    </div>
  );
}
